# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
stages:
  - build
  - test
  - make_deb
image: 192.168.12.16:5000/sunny-ctirobot/cti_ade_base_humble:latest
.tags: &tag
  - humble

build:
  tags:
    - humble
  stage: build
  script:
    - MAKEFLAGS=-j12 colcon build --parallel-workers=24
    - tar -czvf build.tar.gz build
    - tar -czvf install.tar.gz install
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  artifacts:
    paths:
      - build.tar.gz
      - install.tar.gz
    expire_in: 30 mins
# run tests using the binary built before
test:
  tags:
    - humble
  stage: test
  # rules:
  #  - when: manual
  before_script:
    - tar -xzvf build.tar.gz
    - tar -xzvf install.tar.gz
  script:
    - MAKEFLAGS=-j12 colcon test --parallel-workers=24
  needs:
    - build


make_deb:
  tags:
    - humble
  stage: make_deb
  script:
    - rosdep update
    - sed -i 's/my $ignore_missing_info = 0;/my $ignore_missing_info = 1;/g' /usr/bin/dpkg-shlibdeps
    - bash .make_deb.sh
    - bash .upload.sh
  artifacts:
    paths:
      - "*.deb"
    expire_in: 1 week
  needs:
    - test
